### ISSUE TITLE
ImportError: cannot import name collections_abc

### ISSUE THREAD

**Issue by kenwoodhf** [kcjengr/qtpyvcp#102]
(Please fill in this issue template with as much information as you can about the 
circumstances under which the issue occurred, and the steps needed to reproduce it.)

## Steps to reproduce the problem

(provide as detailed a step by step as you can) 

 1.nstalled LinuxCNC Debian  2. 8.2  4.19.0-9-rt
 2. installed Probe Basic as per quick start install

## This is what I expected to happen

to launch probe basic

## This is what happened instead

program loads for a second and then shows an error screen

## It worked properly before this

new installation/home/jan/linuxcnc/configs/probe_basic/config/probe_basic/sim.log
[sim.log](https://github.com/kcjengr/qtpyvcp/files/8083092/sim.log)
/home/jan/linuxcnc/configs/probe_basic/config/probe_basic/custom_config.yml
## Traceback

```python
Traceback (most recent call last):
  File "/home/jan/.local/bin/probe_basic", line 10, in <module>
    sys.exit(main())
  File "/home/jan/.local/lib/python2.7/site-packages/probe_basic/__init__.py", line 20, in main
    qtpyvcp.run_vcp(opts, VCP_CONFIG_FILE)
  File "/home/jan/.local/lib/python2.7/site-packages/qtpyvcp/__init__.py", line 27, in run_vcp
    run(*args, **kwargs)
  File "/home/jan/.local/lib/python2.7/site-packages/qtpyvcp/app/__init__.py", line 129, in run
    launch_application(opts, config)
  File "/home/jan/.local/lib/python2.7/site-packages/qtpyvcp/app/launcher.py", line 66, in launch_application
    loadPlugins(config['data_plugins'])
  File "/home/jan/.local/lib/python2.7/site-packages/qtpyvcp/app/launcher.py", line 222, in loadPlugins
    registerPluginFromClass(plugin_id=plugin_id, plugin_cls=cls, args=args, kwargs=kwargs)
  File "/home/jan/.local/lib/python2.7/site-packages/qtpyvcp/plugins/__init__.py", line 71, in registerPluginFromClass
    plugin_cls = getattr(importlib.import_module(modname), clsname)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/jan/.local/lib/python2.7/site-packages/qtpyvcp/plugins/file_locations.py", line 11, in <module>
    from pyudev.pyqt5 import MonitorObserver
  File "/home/jan/.local/lib/python2.7/site-packages/pyudev/__init__.py", line 48, in <module>
    from pyudev.core import Context, Enumerator
  File "/home/jan/.local/lib/python2.7/site-packages/pyudev/core.py", line 39, in <module>
    from pyudev.device import Devices
  File "/home/jan/.local/lib/python2.7/site-packages/pyudev/device/__init__.py", line 26, in <module>
    from ._device import Attributes, Device, Devices, Tags
  File "/home/jan/.local/lib/python2.7/site-packages/pyudev/device/_device.py", line 37, in <module>
    from six.moves import collections_abc
ImportError: cannot import name collections_abc
```

## Options

```json
{
    "command_line_args": null, 
    "config_file": "/home/jan/linuxcnc/configs/probe_basic/config/probe_basic/custom_config.yml", 
    "confirm_exit": false, 
    "develop": false, 
    "fullscreen": null, 
    "help": false, 
    "hide_cursor": false, 
    "hide_menu_bar": false, 
    "hide_status_bar": false, 
    "info": false, 
    "ini": "/home/jan/linuxcnc/configs/probe_basic/config/probe_basic/probe_basic.ini", 
    "log_file": "/home/jan/linuxcnc/configs/probe_basic/config/probe_basic/sim.log", 
    "log_level": "DEBUG", 
    "maximize": null, 
    "perfmon": false, 
    "position": "0x0", 
    "qt_api": null, 
    "size": null, 
    "stylesheet": null, 
    "theme": null, 
    "version": false
}
```

## System Info
```
 * Description:	Debian GNU/Linux 10 (buster)
 * Kernel: 4.19.0-18-rt-amd64
 * Qt version: v5.11.3
 * Qt bindings: PyQt5 v5.11.3
 * LinuxCNC version: v2.8.2-11-g6a3d0a434
 * QtPyVCP version: v0.3.19
```

## Attachments

Please also find and attach the following files, along with any others that may be helpful:
* /home/jan/linuxcnc/configs/probe_basic/config/probe_basic/sim.log
* /home/jan/linuxcnc/configs/probe_basic/config/probe_basic/custom_config.yml

**Comment by kenwoodhf** [comment]
/home/jan/linuxcnc/configs/probe_basic/config/probe_basic/custom_config.yml
/home/jan/linuxcnc/configs/probe_basic/config/probe_basic/sim.log

Sorry if I am not getting all the info in correctly. Not very good at this.
Jan

**Comment by kenwoodhf** [comment]
Hi
 found a post that said to update pip six  entered pip install -U six and it fixed the problem.
