### ISSUE TITLE
TypeError: write() argument 1 must be unicode, not str

### ISSUE THREAD

**Issue by Herican** [kcjengr/qtpyvcp#104]
1.  Ich kann in Probebasic keine Werkzeugtabelle(Tolls) speichern, wenn ich auf speichern gehe, kommt immer folgende Fehlermeldung
 

 Ich habe heute Probebasic neu, nach folgender vorgehensweise Installiert:
 https://kcjengr.github.io/probe_basic/quick_start.html

## Traceback

```python
Traceback (most recent call last):
  File "/home/dieter/.local/lib/python2.7/site-packages/qtpyvcp/widgets/input_widgets/tool_table.py", line 252, in saveToolTable
    self.tool_model.saveToolTable()
  File "/home/dieter/.local/lib/python2.7/site-packages/qtpyvcp/widgets/input_widgets/tool_table.py", line 200, in saveToolTable
    self.tt.saveToolTable(self._tool_table, self._columns)
  File "/home/dieter/.local/lib/python2.7/site-packages/qtpyvcp/plugins/tool_table.py", line 423, in saveToolTable
    fh.write('\n'.join(lines))
TypeError: write() argument 1 must be unicode, not str
```

## Options

```json
{
    "command_line_args": null, 
    "config_file": null, 
    "confirm_exit": null, 
    "develop": false, 
    "fullscreen": null, 
    "help": false, 
    "hide_cursor": false, 
    "hide_menu_bar": false, 
    "hide_status_bar": false, 
    "info": false, 
    "ini": "/home/dieter/linuxcnc/configs/Axis_Grundeinst_Original_ProbeB/CNC_Probe_Basic.ini", 
    "log_file": "/home/dieter/qtpyvcp.log", 
    "log_level": null, 
    "maximize": null, 
    "perfmon": false, 
    "position": null, 
    "qt_api": null, 
    "size": null, 
    "stylesheet": null, 
    "theme": null, 
    "version": false
}
```

## System Info
```
 * Description:	Debian GNU/Linux 10 (buster)
 * Kernel: 4.19.0-19-rt-amd64
 * Qt version: v5.11.3
 * Qt bindings: PyQt5 v5.11.3
 * LinuxCNC version: v2.8.2-11-g6a3d0a434
 * QtPyVCP version: v0.3.19+15.g3ad0cc9c
```

## Attachments

Please also find and attach the following files, along with any others that may be helpful:
* /home/dieter/qtpyvcp.log
* None
[qtpyvcp.log](https://github.com/kcjengr/qtpyvcp/files/8289339/qtpyvcp.log)

**Comment by Herican** [comment]
Vielen Dank, 
hab es gelöst, habe eine neue Tool.tbl erstellt mit mehreren Einträgen, dann hat es funktioniert. Die tool.tbl war komplett leer, das war vermutlich der Fehler. 

jetzt habe ich aber noch ein weiteres Problem dass sich die G54 bis G59 Werte nicht einstellen lassen.
Wenn ich werte in die Tabelle eintragen will  geht es aber beim speichern bringt er mir tubiose werte zurück
![Bildschirmfoto zu 2022-03-18 17-03-18](https://user-images.githubusercontent.com/76747745/159039213-fc616c8c-bece-463a-b484-2b0c79b5f656.png)

ich habe in einem Video auch gesehen das man die G werte auch dirket mit der Tastatur vogeben kann im unteren mittleren Fenster, das geht bei mir auch nicht.
Könnten Sie mir da nochmals helfen, leider bin noch nicht so tief in diesen thema drin. 

Danke 
Dieter
.

**Comment by Herican** [comment]
Ich habe jetzt eine neue INI Datei erzeugt, jetzt lässt sich auch wieder die Gxx werte speichern.
