### ISSUE TITLE
ImportError: No module named probe_basic_rc

### ISSUE THREAD

**Issue by ianflowe** [kcjengr/qtpyvcp#106]
(Please fill in this issue template with as much information as you can about the 
circumstances under which the issue occurred, and the steps needed to reproduce it.)

## Steps to reproduce the problem

(provide as detailed a step by step as you can) 

 1.loaded linuxcnc 
 2.then loaded python
 3.then loaded probe basic
 4.when rebooted i get this unhandled exception - import error

## This is what I expected to happen

(explain what you thought should have happened)

## This is what happened instead

(explain what happened instead)

## It worked properly before this

(did it work before? what changed?)

## Traceback

```python
Traceback (most recent call last):
  File "/home/ian/.local/bin/probe_basic", line 11, in <module>
    load_entry_point('probe-basic', 'gui_scripts', 'probe_basic')()
  File "/home/ian/probe_basic/probe_basic/__init__.py", line 20, in main
    qtpyvcp.run_vcp(opts, VCP_CONFIG_FILE)
  File "/home/ian/.local/lib/python2.7/site-packages/qtpyvcp/__init__.py", line 27, in run_vcp
    run(*args, **kwargs)
  File "/home/ian/.local/lib/python2.7/site-packages/qtpyvcp/app/__init__.py", line 129, in run
    launch_application(opts, config)
  File "/home/ian/.local/lib/python2.7/site-packages/qtpyvcp/app/launcher.py", line 78, in launch_application
    loadWindows(config['windows'])
  File "/home/ian/.local/lib/python2.7/site-packages/qtpyvcp/app/launcher.py", line 228, in loadWindows
    window = _initialize_object_from_dict(window_dict)
  File "/home/ian/.local/lib/python2.7/site-packages/qtpyvcp/app/launcher.py", line 203, in _initialize_object_from_dict
    obj = _get_object_by_referance(provider)
  File "/home/ian/.local/lib/python2.7/site-packages/qtpyvcp/app/launcher.py", line 191, in _get_object_by_referance
    return getattr(importlib.import_module(modname), attrname)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ian/probe_basic/probe_basic/probe_basic.py", line 13, in <module>
    import probe_basic_rc
ImportError: No module named probe_basic_rc
```

## Options

```json
{
    "command_line_args": null, 
    "config_file": "/home/ian/linuxcnc/configs/probe_basic/custom_config.yml", 
    "confirm_exit": false, 
    "develop": false, 
    "fullscreen": null, 
    "help": false, 
    "hide_cursor": false, 
    "hide_menu_bar": false, 
    "hide_status_bar": false, 
    "info": false, 
    "ini": "/home/ian/linuxcnc/configs/probe_basic/probe_basic.ini", 
    "log_file": "/home/ian/linuxcnc/configs/probe_basic/sim.log", 
    "log_level": "DEBUG", 
    "maximize": null, 
    "perfmon": false, 
    "position": "0x0", 
    "qt_api": null, 
    "size": null, 
    "stylesheet": null, 
    "theme": null, 
    "version": false
}
```

## System Info
```
 * Description:	Debian GNU/Linux 10 (buster)
 * Kernel: 4.19.0-17-rt-amd64
 * Qt version: v5.11.3
 * Qt bindings: PyQt5 v5.11.3
 * LinuxCNC version: v2.8.2-11-g6a3d0a434
 * QtPyVCP version: v0.3.19
```

## Attachments

Please also find and attach the following files, along with any others that may be helpful:
* /home/ian/linuxcnc/configs/probe_basic/sim.log
* /home/ian/linuxcnc/configs/probe_basic/custom_config.yml

**Comment by ianflowe** [comment]
I am a new Linuxcnc user and have not used Linux before so would appreciate any help to clear these errors

**Comment by ianflowe** [comment]
Thanks for your Help

**Comment by TurBoss** [comment]
got it working?
