### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)

### ISSUE THREAD

**Issue by Woki-Leo** [kcjengr/qtpyvcp#121]
(Please fill in this issue template with as much information as you can about the 
circumstances under which the issue occurred, and the steps needed to reproduce it.)

Fresh install after running axis for a while
had trouble installing the conversational. had to skip and couldnt install manually. now on pb startup i get this
[qtpyvcp.log](https://github.com/kcjengr/qtpyvcp/files/11592214/qtpyvcp.log)
is this similar to issue #61 ? 

## Steps to reproduce the problem

(provide as detailed a step by step as you can) 

 1.
 2.
 3.

## This is what I expected to happen

(explain what you thought should have happened)

## This is what happened instead

(explain what happened instead)

## It worked properly before this

(did it work before? what changed?)

## Traceback

```python
Traceback (most recent call last):
  File "/home/leo/.local/bin/probe_basic", line 8, in <module>
    sys.exit(main())
  File "/home/leo/.local/lib/python2.7/site-packages/probe_basic/__init__.py", line 20, in main
    qtpyvcp.run_vcp(opts, VCP_CONFIG_FILE)
  File "/home/leo/.local/lib/python2.7/site-packages/qtpyvcp/__init__.py", line 27, in run_vcp
    run(*args, **kwargs)
  File "/home/leo/.local/lib/python2.7/site-packages/qtpyvcp/app/__init__.py", line 129, in run
    launch_application(opts, config)
  File "/home/leo/.local/lib/python2.7/site-packages/qtpyvcp/app/launcher.py", line 78, in launch_application
    loadWindows(config['windows'])
  File "/home/leo/.local/lib/python2.7/site-packages/qtpyvcp/app/launcher.py", line 228, in loadWindows
    window = _initialize_object_from_dict(window_dict)
  File "/home/leo/.local/lib/python2.7/site-packages/qtpyvcp/app/launcher.py", line 208, in _initialize_object_from_dict
    return obj(*args, **kwargs)
  File "/home/leo/.local/lib/python2.7/site-packages/probe_basic/probe_basic.py", line 24, in __init__
    super(ProbeBasic, self).__init__(*args, **kwargs)
  File "/home/leo/.local/lib/python2.7/site-packages/qtpyvcp/widgets/form_widgets/main_window.py", line 57, in __init__
    self.setMenuBar(self.buildMenuBar(menu))
  File "/home/leo/.local/lib/python2.7/site-packages/qtpyvcp/widgets/form_widgets/main_window.py", line 246, in buildMenuBar
    recursiveAddItems(menu_bar, menus)
  File "/home/leo/.local/lib/python2.7/site-packages/qtpyvcp/widgets/form_widgets/main_window.py", line 231, in recursiveAddItems
    recursiveAddItems(new_menu, items)
  File "/home/leo/.local/lib/python2.7/site-packages/qtpyvcp/widgets/form_widgets/main_window.py", line 235, in recursiveAddItems
    new_menu = _initialize_object_from_dict(item, parent=menu)
  File "/home/leo/.local/lib/python2.7/site-packages/qtpyvcp/app/launcher.py", line 208, in _initialize_object_from_dict
    return obj(*args, **kwargs)
  File "/home/leo/.local/lib/python2.7/site-packages/qtpyvcp/widgets/recent_files_menu.py", line 56, in __init__
    self.update(files or self.status.recent_files())
  File "/home/leo/.local/lib/python2.7/site-packages/qtpyvcp/widgets/recent_files_menu.py", line 61, in update
    fname = fname.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)
```

## Options

```json
{
    "command_line_args": null, 
    "config_file": null, 
    "confirm_exit": null, 
    "develop": false, 
    "fullscreen": null, 
    "help": false, 
    "hide_cursor": false, 
    "hide_menu_bar": false, 
    "hide_status_bar": false, 
    "info": false, 
    "ini": "/home/leo/linuxcnc/configs/leos_cnc/leos_cnc.ini", 
    "log_file": "/home/leo/qtpyvcp.log", 
    "log_level": null, 
    "maximize": null, 
    "perfmon": false, 
    "position": null, 
    "qt_api": null, 
    "size": null, 
    "stylesheet": null, 
    "theme": null, 
    "version": false
}
```

## System Info
```
 * Description:	Debian GNU/Linux 10 (buster)
 * Kernel: 4.19.0-24-rt-amd64
 * Qt version: v5.11.3
 * Qt bindings: PyQt5 v5.11.3
 * LinuxCNC version: v2.8.4
 * QtPyVCP version: v0.3.19+18.gee2deacc
```

## Attachments
log
[qtpyvcp.log](https://github.com/kcjengr/qtpyvcp/files/11592217/qtpyvcp.log)

**Comment by Woki-Leo** [comment]
the issue was 3 .ngc File names containing `Ä`
