### ISSUE TITLE
When system language in chinese, pharse files will have error decoding

### ISSUE THREAD

**Issue by xzkeee** [kcjengr/qtpyvcp#141]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qtpyvcp/widgets/input_widgets/file_system.py", line 111, in data
    date = parse(data)
           ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 2024/3/17 上午12:48

i am using prob basic and system language is in chinese; everytime go files section it raise this error,  it try to get last modified date and system return a chinese string time and code can not handle it.  Is this qtpyvcp problem or probebasic problem tho.

**Comment by TurBoss** [comment]
fixed in main branch

thank you
