### ISSUE TITLE
AttributeError: 'Status' object has no attribute 'backplot_gcode_error'

### ISSUE THREAD

**Issue by hadcom** [kcjengr/qtpyvcp#38]
(Please fill in this issue template with as much information as you can about the 
circumstances under which the issue occurred, and the steps needed to reproduce it.)

## Steps to reproduce the problem

(provide as detailed a step by step as you can) 

 1.
 2.
 3.

## This is what I expected to happen

(explain what you thought should have happened)

## This is what happened instead

(explain what happened instead)

## It worked properly before this

(did it work before? what changed?)

## Traceback

```python
Traceback (most recent call last):
  File "/home/vmc/qtpyvcp/qtpyvcp/widgets/display_widgets/gcode_backplot/gcode_backplot.py", line 96, in loadBackplot
    self.load(fname)
  File "/home/vmc/qtpyvcp/qtpyvcp/widgets/display_widgets/gcode_backplot/qbackplot.py", line 273, in load
    self.report_gcode_error(result, seq, filename)
  File "/home/vmc/qtpyvcp/qtpyvcp/widgets/display_widgets/gcode_backplot/gcode_backplot.py", line 136, in report_gcode_error
    STATUS.backplot_gcode_error.emit(msg)
AttributeError: 'Status' object has no attribute 'backplot_gcode_error'
```

## Options

```json
{
    "command_line_args": null, 
    "config_file": null, 
    "confirm_exit": null, 
    "develop": false, 
    "fullscreen": null, 
    "help": false, 
    "hide_cursor": false, 
    "hide_menu_bar": false, 
    "hide_status_bar": false, 
    "ini": "/home/vmc/linuxcnc/configs/VMC/VMC.ini", 
    "log_file": "/home/vmc/qtpyvcp.log", 
    "log_level": null, 
    "maximize": null, 
    "perfmon": false, 
    "position": null, 
    "pref_file": null, 
    "qt_api": null, 
    "size": null, 
    "stylesheet": null, 
    "theme": null, 
    "version": false
}
```

## System Info
```
 * Description:	Debian GNU/Linux 9.12 (stretch)
 * Kernel: 4.9.0-12-rt-amd64
 * Qt version: v5.7.1
 * Qt bindings: PyQt5 v5.7
 * LinuxCNC version: v2.9.0-pre0-2099-gcf6945d9b
 * QtPyVCP version: v0.3.7+71.g21ee0b15
```

## Attachments

Please also find and attach the following files, along with any others that may be helpful:
* /home/vmc/qtpyvcp.log
* None

**Comment by joco-nz** [comment]
I think this is now stale with no further reports in 2 yrs. Closing.
