### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'poly_data'

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/qtpyvcp#55]
(Please fill in this issue template with as much information as you can about the 
circumstances under which the issue occurred, and the steps needed to reproduce it.)

## Steps to reproduce the problem

(provide as detailed a step by step as you can) 

 1. just traing to change tool in the main tab page
 2.
 3.

## This is what I expected to happen

(explain what you thought should have happened)

## This is what happened instead

(explain what happened instead)

## It worked properly before this

(did it work before? what changed?)

## Traceback

```python
Traceback (most recent call last):
  File "/home/cnc/.local/lib/python2.7/site-packages/qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py", line 397, in load_program
    self.canon.draw_lines()
  File "/home/cnc/.local/lib/python2.7/site-packages/qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py", line 220, in draw_lines
    path_actor.poly_data.SetPoints(path_actor.points)
AttributeError: 'NoneType' object has no attribute 'poly_data'
```

## Options

```json
{
    "command_line_args": null, 
    "config_file": null, 
    "confirm_exit": null, 
    "develop": false, 
    "fullscreen": true, 
    "help": false, 
    "hide_cursor": false, 
    "hide_menu_bar": false, 
    "hide_status_bar": false, 
    "ini": "/home/cnc/linuxcnc/configs/GnevkoVCP/GnevkoVCP.ini", 
    "log_file": "/home/cnc/qtpyvcp.log", 
    "log_level": null, 
    "maximize": true, 
    "perfmon": false, 
    "position": "0x0", 
    "pref_file": null, 
    "qt_api": null, 
    "size": "1920x1080", 
    "stylesheet": null, 
    "theme": null, 
    "version": false
}
```

## System Info
```
 * Description:	Debian GNU/Linux 10 (buster)
 * Kernel: 4.19.0-12-rt-amd64
 * Qt version: v5.11.3
 * Qt bindings: PyQt5 v5.11.3
 * LinuxCNC version: v2.9.0-pre0-2909-gca06fc273
 * QtPyVCP version: v0.3.6
```

## Attachments

Please also find and attach the following files, along with any others that may be helpful:
* /home/cnc/qtpyvcp.log
* None

**Comment by Gnevko** [comment]
After installation of the current muster version in development mode - it works now
