### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'setNotify'

### ISSUE THREAD

**Issue by gesamtplan** [kcjengr/qtpyvcp#67]
(Please fill in this issue template with as much information as you can about the 
circumstances under which the issue occurred, and the steps needed to reproduce it.)

## Steps to reproduce the problem

(provide as detailed a step by step as you can) 

 1.
 2.
 3.

## This is what I expected to happen

(explain what you thought should have happened)

## This is what happened instead

(explain what happened instead)

## It worked properly before this

(did it work before? what changed?)

## Traceback

```python
Traceback (most recent call last):
  File "/home/charon/.local/lib/python2.7/site-packages/qtpyvcp/plugins/notifications.py", line 126, in timerEvent
    self.captureMessage('error', msg)
  File "/home/charon/.local/lib/python2.7/site-packages/qtpyvcp/plugins/notifications.py", line 82, in captureMessage
    self.notification_dispatcher.setNotify(m_type, msg)
AttributeError: 'NoneType' object has no attribute 'setNotify'
```

## Options

```json
{
    "chooser": false, 
    "command_line_args": null, 
    "config_file": "/home/charon/linuxcnc/configs/sim.qtpyvcp/custom_config.yml", 
    "confirm_exit": false, 
    "develop": false, 
    "fullscreen": null, 
    "help": false, 
    "hide_cursor": false, 
    "hide_menu_bar": false, 
    "hide_status_bar": false, 
    "info": false, 
    "ini": "/home/charon/linuxcnc/configs/sim.qtpyvcp/mini.ini", 
    "log_file": "/home/charon/linuxcnc/configs/sim.qtpyvcp/sim.log", 
    "log_level": "WARN", 
    "maximize": null, 
    "perfmon": false, 
    "position": "0x0", 
    "qt_api": null, 
    "size": null, 
    "stylesheet": null, 
    "theme": null, 
    "vcp": "mini", 
    "version": false
}
```

## System Info
```
 * Description:	Debian GNU/Linux 10 (buster)
 * Kernel: 4.19.0-11-rt-amd64
 * Qt version: v5.11.3
 * Qt bindings: PyQt5 v5.11.3
 * LinuxCNC version: v2.8.1
 * QtPyVCP version: v0.3.11
```

## Attachments

Please also find and attach the following files, along with any others that may be helpful:
* /home/charon/linuxcnc/configs/sim.qtpyvcp/sim.log
* /home/charon/linuxcnc/configs/sim.qtpyvcp/custom_config.yml

**Comment by gesamtplan** [comment]
Seems I am to stupid to install cause i got the same Error as described on Dec 15th by sebastianm1986.

**Comment by gesamtplan** [comment]
[sim.log](https://github.com/kcjengr/qtpyvcp/files/5828252/sim.log)
